/** Estados de la máquina de conversación del chatbot WhatsApp */
export const ESTADOS = {
  MENU_PRINCIPAL: 'MENU_PRINCIPAL',
  MENU_ALUMNO: 'MENU_ALUMNO',
  MENU_NUEVO: 'MENU_NUEVO',
  ESPERANDO_DNI: 'ESPERANDO_DNI',
  ESPERANDO_CONSULTA: 'ESPERANDO_CONSULTA',
  /** Tras "hablar con profesora": el bot no contesta; solo reenvía y espera *menu* */
  CON_PROFESORA: 'CON_PROFESORA',
  ESPERANDO_LIBERAR: 'ESPERANDO_LIBERAR',
  ESPERANDO_RECUPERAR: 'ESPERANDO_RECUPERAR',
  /** Cambiar turno fijo: elegir origen → destino → confirmar */
  ESPERANDO_CAMBIAR_ORIGEN: 'ESPERANDO_CAMBIAR_ORIGEN',
  ESPERANDO_CAMBIAR_DESTINO: 'ESPERANDO_CAMBIAR_DESTINO',
  ESPERANDO_CAMBIAR_CONFIRM: 'ESPERANDO_CAMBIAR_CONFIRM',
  NUEVO_NOMBRE: 'NUEVO_NOMBRE',
  NUEVO_APELLIDO: 'NUEVO_APELLIDO',
  NUEVO_DNI: 'NUEVO_DNI',
  NUEVO_EMAIL: 'NUEVO_EMAIL',
  NUEVO_ACTIVIDAD: 'NUEVO_ACTIVIDAD',
  NUEVO_HORARIO: 'NUEVO_HORARIO',
};

/** Acciones pendientes cuando el usuario ingresa el DNI */
export const ACCIONES_DNI = {
  VENCIMIENTO: 'VENCIMIENTO',
  CANCELAR: 'CANCELAR',
  RECUPERAR: 'RECUPERAR',
  HORARIOS: 'HORARIOS',
  CAMBIAR: 'CAMBIAR',
};
